<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="BDTUDV31328" name="decModule20Again.Add_Customer_Create_NI_WO" tests="1" failures="0" timestamp="7 Jan 2017 07:10:32 GMT" time="119.090" errors="1">
  <testcase name="Add_Customer_NI_WorkOrder" time="119.090" classname="decModule20Again.Add_Customer_Create_NI_WO">
    <error type="java.lang.IllegalArgumentException" message="Cannot find elements with a null id attribute.">
      <![CDATA[java.lang.IllegalArgumentException: Cannot find elements with a null id attribute.
	at org.openqa.selenium.By.id(By.java:53)
	at decModule20Again.BaseTestDec25.getElement(BaseTestDec25.java:228)
	at decModule20Again.BaseTestDec25.Callertype(BaseTestDec25.java:194)
	at decModule20Again.Add_Customer_Create_NI_WO.Add_Customer_NI_WorkOrder(Add_Customer_Create_NI_WO.java:111)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:816)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1124)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:774)
	at org.testng.TestRunner.run(TestRunner.java:624)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:359)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:354)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:312)
	at org.testng.SuiteRunner.run(SuiteRunner.java:261)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1215)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
	at org.testng.TestNG.run(TestNG.java:1048)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:126)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:152)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:57)
]]>
    </error>
  </testcase> <!-- Add_Customer_NI_WorkOrder -->
</testsuite> <!-- decModule20Again.Add_Customer_Create_NI_WO -->
